coverage:
  status:
    project:
      default:
        target: 50%
        threshold: 1%
        informational: false
    patch:
      default:
        target: 50%
        threshold: 1%
        informational: false

ignore:
  - "**/*_test.go"
